class 'C' cannot inherit from 'B' as it has been declared as 'final' 1>------ Build started: Project: override_specifier, Configuration: Debug Win32 ------ 1>override_specifier.cpp 1>override_specifier.cpp(16,1): error C3246: 1>override_specifier.cpp(9): message :  see declaration of 'B' 1>Done building project "override_specifier.vcxproj" -- FAILED. ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========